"""Few changes

Revision ID: d8ec7a9eac58
Revises: 7186c3266df7
Create Date: 2023-07-19 00:40:24.203345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ec7a9eac58'
down_revision = '7186c3266df7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_todo_todo_desc', table_name='todo')
    op.create_unique_constraint(None, 'todo', ['todo_desc'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'todo', type_='unique')
    op.create_index('ix_todo_todo_desc', 'todo', ['todo_desc'], unique=False)
    # ### end Alembic commands ###
